apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "moodle-with-efs.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 100Gi