apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "moodle-with-efs.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 100Gi # This value does not limit the size of your Amazon EFS file system.
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efsId }}