apiVersion: v1
kind: Service
metadata:
  name: {{ include "moodle-with-efs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "moodle-with-efs.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: moodle-with-efs
    {{- include "moodle-with-efs.selectorLabels" . | nindent 4 }}